### ISSUE TITLE
width and height seem wrong

### ISSUE THREAD

**Issue by yalin** [jimkang/g-i-s#10]
I think the width and height are wrong. I looked from the console and my console output is like this ; 

![image](https://user-images.githubusercontent.com/652545/87109907-5e0fa300-c240-11ea-901a-fdd154d2ee89.png)

image URL: https://i.pinimg.com/originals/68/ed/8d/68ed8da96b2016ded1c95960684e4fcb.jpg
and the image dimensions are the opposite. 
width : 500
height: 700 

does it work just like this or am I doing something wrong?

_note : don't ask me why this picture :rofl:. I was just coding a program doing random google images searches and this came up._

**Comment by jimkang** [comment]
Haha, That's an amazing picture!

Thanks for reporting the issue. It's fixed in 2.1.6, so if you update to the latest version of this package, that should take care of it.
