### ISSUE TITLE
I get a CORS error when I try to use it in my app served on local host, how do I fix this?

### ISSUE THREAD

**Issue by InkyWinky** [jimkang/g-i-s#17]
```
async getImgUrl(){
    var gis = require('g-i-s');
    gis('cats', logResults);
    
    function logResults(error, results) {
      if (error) {
        console.log(error);
      }
      else {
        console.log(JSON.stringify(results, null, '  '));
        return results[0]
      }
    }
```

yields this error: Access to fetch at 'http://images.google.com/search?tbm=isch&q=cats%20-site%3Agstatic.com' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
I am running a cors-anywhere proxy

**Comment by jimkang** [comment]
Sorry, this package won't work in a browser. It's only meant to be used on the server side in Node, which doesn't care about CORS.

**Comment by InkyWinky** [comment]
Thank you for replying! I managed to make it work actually with a proxy server and editing the index.js file locally very slightly. Thank you very much for creating this package.
