### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by DevDokus** [jimkang/g-i-s#9]
This module has stopped working a couple weeks ago. 
It is not returning any information anymore. 
As of it's description it is saying that in 2018 they 
concluded it still worked. So my guess is that this module 
has not been updated in that time frame.

Is there a update going to happen in the future ?

**Comment by jimkang** [comment]
Just tried it. Seems to still work. Are you using 2.1.5?

**Comment by jimkang** [comment]
Well, let me know if you have problems when you try the current version.
